export { default as Dashboard } from './Dashboard';
export { default as Header } from './Header';
export { default as Sidebar } from './Sidebar';
export { default as CourseGrid } from './CourseGrid';
export { default as CourseCard } from './CourseCard';
export { default as PageHeader } from './PageHeader';
export { default as LoadingSpinner } from './LoadingSpinner';
export { default as AddCourseModal } from './AddCourseModal';
export { default as SearchBar } from './SearchBar'; 